// <auto-generated />
using Catalog.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catalog.DAL.Migrations
{
    [DbContext(typeof(CatalogDataContext))]
    partial class CatalogDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Catalog.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FreeCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageSrc")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Season")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("WholesalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "TOYO",
                            CategoryId = 2,
                            Code = "234hgjX",
                            Count = 10,
                            FreeCount = 7,
                            Model = "XCV 123x238x16",
                            RetailPrice = 220.00m,
                            Season = "Winter",
                            Summary = "tire 24 67 78",
                            WholesalePrice = 99.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "TOYO",
                            CategoryId = 2,
                            Code = "234hgjX1",
                            Count = 10,
                            FreeCount = 7,
                            Model = "FG 12x43x56",
                            RetailPrice = 210.00m,
                            Season = "Summer",
                            Summary = "tire 21 60 77",
                            WholesalePrice = 97.00m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "TOYO",
                            CategoryId = 2,
                            Code = "234hgjv2",
                            Count = 10,
                            FreeCount = 7,
                            Model = "HG 12x32x34",
                            RetailPrice = 212.00m,
                            Season = "Winter",
                            Summary = "tire 27 64 79",
                            WholesalePrice = 98.9m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Bosh",
                            CategoryId = 1,
                            Code = "234hg21m",
                            Count = 10,
                            FreeCount = 7,
                            Model = "GF124G",
                            RetailPrice = 102.00m,
                            Summary = "AGM 26 78",
                            WholesalePrice = 99.99m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Bosh",
                            CategoryId = 1,
                            Code = "67nbbb7",
                            Count = 10,
                            FreeCount = 7,
                            Model = "LC224X",
                            RetailPrice = 99.00m,
                            Summary = "AGM 66 78 98",
                            WholesalePrice = 91.99m
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Bosh",
                            CategoryId = 1,
                            Code = "46bfhj7X",
                            Count = 10,
                            FreeCount = 7,
                            Model = "JS994M",
                            RetailPrice = 98.00m,
                            Summary = "AGM 11 66 77",
                            WholesalePrice = 92.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
